[package]
name = "tail-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3"
num = "0.4"
regex = "1"
once_cell = "1"
[dev-dependencies]
assert_cmd = "2"
predicates = "2"
rand = "0.8"