[project]
name = "tutorial"
version = "0.1.0"
description = "tutorial spider"
requires-python = ">=3.11"
dependencies = [
    "pillow>=11.0.0",
    "scrapy>=2.11.2",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
