[package]
name = "ajax"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json", "cookies", "socks"] }
url = "2.2.2"
serde_json = "1"
dirs = "4.0.0"